import os

AZURE_STORAGE_UPLOAD = True
AZURE_STORAGE_ACCOUNT_NAME = "lillorgiddata"
AZURE_STORAGE_CONTAINER_NAME = "data"
AZURE_STORAGE_CONNECTION_STRING = os.getenv("AZURE_STORAGE_CONNECTION_STRING")

AZURE_POSTGRES_CONNECTION_STRING = os.getenv("AZURE_POSTGRES_CONNECTION_STRING")

THREESIXTYGIVING_DATASTORE_POSTGRES_CONNECTION_STRING = os.getenv("THREESIXTYGIVING_DATASTORE_POSTGRES_CONNECTION_STRING")


# No / at end of SOLR_URL please
SOLR_URL = os.getenv("SOLR_URL", "http://localhost:8983/solr")

SOLR_LISTS_CORE = os.getenv("SOLR_LISTS_CORE", "lillorgidlists")
SOLR_DATA_CORE = os.getenv("SOLR_DATA_CORE", "lillorgiddata")

SOLR_USERNAME = os.getenv("SOLR_USERNAME", "user")
SOLR_PASSWORD = os.getenv("SOLR_PASSWORD", "pass")
